services:
  usuariosdb:
    image: mysql:5.7
    container_name: usuariosdb
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=usuariosdb
    volumes:
      - ./db/usuariosdb/:/docker-entrypoint-initdb.d
    networks:
      - mi_red

  asignaturasdb:
    image: mysql:5.7
    container_name: asignaturasdb
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=asignaturasdb
    volumes:
      - ./db/asignaturasdb/:/docker-entrypoint-initdb.d
    networks:
      - mi_red

  cursosdb:
    image: mysql:5.7
    container_name: cursosdb
    ports:
      - "32002:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cursosdb
    volumes:
      - ./db/cursosdb/:/docker-entrypoint-initdb.d
    networks:
      - mi_red

  usuarios:
    build:
      context: ./microservicios/usuarios
    container_name: usuarios
    ports:
      - "3005:3005"
    networks:
      - mi_red
    depends_on:
      - usuariosdb

  asignaturas:
    build:
      context: ./microservicios/asignaturas
    container_name: asignaturas
    ports:
      - "3006:3006"
    networks:
      - mi_red
    depends_on:
      - asignaturasdb

  cursos:
    build:
      context: ./microservicios/cursos
    container_name: cursos
    ports:
      - "3007:3007"
    networks:
      - mi_red
    depends_on:
      - cursosdb
      - usuarios
      - asignaturas

  graficas:
    build:
      context: ./microservicios/graficas
    container_name: graficas
    ports:
      - "3008:3008"
    networks:
      - mi_red
    depends_on:
      - usuarios
      - cursos

  haproxy:
    build:
      context: ./haproxy
    container_name: haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    networks:
      - mi_red
    depends_on:
      - web1
      - web2

  web1: 
    build:
      context: ./vista
    container_name: web1
    ports:
      - "8080:80"
    networks:
      - mi_red
    depends_on:
      - usuarios
      - asignaturas
      - cursos
      - graficas

  web2: 
    build:
      context: ./vista
    container_name: web2
    ports:
      - "8081:80"
    networks:
      - mi_red
    depends_on:
      - usuarios
      - asignaturas
      - cursos
      - graficas

networks:
  mi_red:
    driver: bridge
