version: '3.8'

services:
  databases:
    image: mysql:5.6
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./databases/usuariosDB/:/docker-entrypoint-initdb.d
      - ./databases/mysql-data/import:/var/lib/mysql-files
      - ../database_vol/mysql-asignaturas-data:/var/lib/mysql
    networks:
      - my-network

  usuarios:
    image: microusuarios
    build:
      context: ./microservicios/usuarios
    ports:
      - "3005:3005"
    depends_on:
      - usuariosDB
    networks:
      - my-network

  asignaturas:
    image: microasignaturas
    build:
      context: ./microservicios/asignaturas
    ports:
      - "3006:3006"
    depends_on:
      - asignaturasDB
    networks:
      - my-network

  cursos:
    image: microcursos
    build:
      context: ./microservicios/cursos
    ports:
      - "3007:3007"
    depends_on:
      - cursosDB
      - usuarios
      - asignaturas
    networks:
      - my-network

  graficas:
    image: micrograficas
    build:
      context: ./microservicios/graficas
    ports:
      - "3008:3008"
    depends_on:
      - usuarios
      - cursos
    networks:
      - my-network

  haproxy:
    build:
      context: ./haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
    networks:
      - my-network

  web1: 
    build:
      context: ./vista
    ports:
      - "8080:80"
    depends_on:
      - usuarios
      - asignaturas
      - cursos
      - graficas
    networks:
      - my-network


  web2: 
    build:
      context: ./vista
    ports:
      - "8081:80"
    depends_on:
      - usuarios
      - asignaturas
      - cursos
      - graficas
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
